### ISSUE TITLE
Proper attribution

### ISSUE THREAD

**Issue by MikeMcl** [ttulka/as-big#1]
Looks good, Tomas.

This is a polite request for you to include my [copyright notice and license](https://github.com/MikeMcl/big.js/blob/master/LICENCE.md) with this software, as it is clearly built very substantially on my hard work.

**Comment by ttulka** [comment]
Hi Mike,
Sure, definitely! I tried to give you the credit already by mentioning you explicitly in the headlines of README. 

I'm just thinking how to do it properly as your license talks about big.js and as-big does differ in some aspects. 

Would you like to create a PR with a solution that you’d be happy with? Or just tell me your vision. Thanks! 

And many thanks for your work, I'm a big fan!

**Comment by MikeMcl** [comment]
Yes, I think I would class this as a "derivative work", and you've done an impressive job.

As the MIT license is the same for both, the easiest solution is probably just to add my copyright to the existing license.

I'll create a PR.

**Comment by ttulka** [comment]
Merged, thank you!
