### ISSUE TITLE
Is it ready to production?

### ISSUE THREAD

**Issue by dalssoft** [ttulka/as-big#3]
Hi. Great work @ttulka! 

Until we have a native decimal type in JS it seems as-big is the best option I found to our financial (in production) applications.

So we'd like to know in what scenarios as-big has been used and if it has been used in production env.

Thanks!

**Comment by ttulka** [comment]
Hi, thanks! 

I can't really talk for all users it is an open source library. 
I have used it in production already, however, not all features extensively. 

Needless to say, the library is based on big.js which is used in production by hundreds of thousands clients. 

In case of any issue, I will do my best to fix it asap.

Also, you may want to wait a few days for updating as-big to AssemblyScript 0.19

**Comment by dalssoft** [comment]
Cool! 

> I have used it in production already, however, not all features extensively.

Is it a financial use case? Does it have to deal with precision bigger than 16 digits?

> Needless to say, the library is based on big.js which is used in production by hundreds of thousands clients.

Sure. The idea is to have a lib with a better performance. I'm assuming that by using WASM as-big has a better performance. Have you done any performance benchmark?

> In case of any issue, I will do my best to fix it asap.

That's great to know! BTW, we would like to send issues and PRs in order to improve as-big (instead of a fork). Is that ok for you?

**Comment by ttulka** [comment]
No financial use, however complex math with big precision. 

Performance is not great in comparison with native numbers, could be an issue in iterating. I haven't done any further benchmarking as it was  not an issue for me. But I recommend doing so if it is for you. 

PRs are not only okay, but also very welcome as this is what FOSS is about :)
