### ISSUE TITLE
Is this supposed to work in Node.js?

### ISSUE THREAD

**Issue by gajus** [ttulka/as-big#4]
...and would there be any benefits to using it that way.

Currently getting `Error: Cannot find module 'as-big'` error.

**Comment by ttulka** [comment]
Could you be more specific about what are you doing?

It is currently working in Node, for instance, the test are running in Node:

```
npm i
npm run asbuild

node tests
```

But this is an [AssemblyScript](https://www.assemblyscript.org/) library, the point is to create WebAssembly modules.
